import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import React from "react";
import '@/lib/orpc.server' // pre-rendering for SSR
import ThemeProvider from "@/components/theme-provider";
import AuthProvider from "@/components/auth-provider";
import {Toaster} from "@/components/ui/sonner";
import {QueryProviders} from "@/lib/query/query-provider";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const RootLayout = ({children,}: Readonly<{ children: React.ReactNode; }>) => {
    return (
        <AuthProvider>
            <html
                lang={"en"}
                suppressHydrationWarning
            >
                <body
                    className={`${geistSans.variable} ${geistMono.variable} antialiased`}
                >
                    <ThemeProvider
                        attribute={"class"}
                        defaultTheme={"system"}
                        enableSystem
                        disableTransitionOnChange
                    >
                        <QueryProviders>
                            {children}
                        </QueryProviders>
                    </ThemeProvider>
                    <Toaster
                        closeButton
                        position={"top-center"}
                        richColors
                    />
                </body>
            </html>
        </AuthProvider>
    );
}

export default RootLayout;